/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package QuanLyTEA.UI;
import QuanLyTEA.model.UserAD;
import QuanLyTEA.TKDAO.LoginDAO;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author Admin
 */
public class DangNhapAD extends javax.swing.JFrame {

    /**
     * Creates new form DangNhapAD
     */
    public DangNhapAD() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtTenDN = new javax.swing.JTextField();
        txtMatKhau = new javax.swing.JPasswordField();
        btnDangNhap = new javax.swing.JButton();
        chkRemember = new javax.swing.JCheckBox();
        chkShow = new javax.swing.JCheckBox();
        timeLabel = new javax.swing.JLabel();
        dateLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 51, 0));
        jLabel2.setText("YIQI-TEA  ADMIN");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, 250, 40));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Username");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Password");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, -1, -1));

        txtTenDN.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 102, 0), 1, true));
        getContentPane().add(txtTenDN, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 230, 20));

        txtMatKhau.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 51, 0), 1, true));
        getContentPane().add(txtMatKhau, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 230, 20));

        btnDangNhap.setBackground(new java.awt.Color(255, 102, 0));
        btnDangNhap.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDangNhap.setForeground(new java.awt.Color(255, 255, 255));
        btnDangNhap.setText("Đăng nhập");
        btnDangNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangNhapActionPerformed(evt);
            }
        });
        getContentPane().add(btnDangNhap, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 240, 110, 30));

        chkRemember.setText("Remember?");
        chkRemember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkRememberActionPerformed(evt);
            }
        });
        getContentPane().add(chkRemember, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 210, -1, 20));

        chkShow.setText("Show/Hide");
        chkShow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkShowActionPerformed(evt);
            }
        });
        getContentPane().add(chkShow, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 180, -1, -1));

        timeLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        timeLabel.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(timeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 0, 80, 20));

        dateLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        dateLabel.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(dateLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 0, 120, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/backgroud.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 280));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void chkRememberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkRememberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkRememberActionPerformed

    private void btnDangNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangNhapActionPerformed
//        try {
//            String tenDN = txtTenDN.getText().trim();
//            String matKhau = new String(txtMatKhau.getPassword()).trim();
//            
//            if (tenDN.isEmpty() || matKhau.isEmpty()) {
//                JOptionPane.showMessageDialog(this, "Vui lòng nhập tên đăng nhập và mật khẩu.");
//                return;
//            }
//            
//            LoginDAO loginDAO = new LoginDAO();
//    UserAD user = null;
//    try {
//        user = loginDAO.login(tenDN, matKhau);
//    } catch (Exception ex) {
//        Logger.getLogger(DangNhapAD.class.getName()).log(Level.SEVERE, null, ex);
//    }
//
//    if (user != null) {
//        JOptionPane.showMessageDialog(this, "Đăng nhập thành công!");
//        GiaoDienTEA mainFrame = new GiaoDienTEA(tenDN); // Truyền tên đăng nhập vào form chính
//        mainFrame.setVisible(true);
//        this.dispose(); // Đóng form đăng nhập
//    } else {
//        JOptionPane.showMessageDialog(this, "Tên đăng nhập hoặc mật khẩu không đúng.");
//    }
//UserAD user = loginDAO.login(tenDN, matKhau);
//
//if (user != null) {
//    // Đăng nhập thành công
//    if (user.isAdmin()) {
//        JOptionPane.showMessageDialog(this, "Đăng nhập thành công với quyền quản trị viên!");
//        GiaoDienTEA mainFrame = new GiaoDienTEA(tenDN); // Truyền tên đăng nhập vào form chính
//        mainFrame.setVisible(true);
//        this.dispose(); // Đóng form đăng nhập
//    } else {
//        JOptionPane.showMessageDialog(this, "Đăng nhập thành công với quyền người dùng!");
//        // Mở giao diện cho người dùng
//        GiaoDienTEA mainFrame = new GiaoDienTEA(tenDN); // Truyền tên đăng nhập vào form chính
//        mainFrame.setVisible(true);
//        this.dispose(); // Đóng form đăng nhập
//    }
//} else {
//    JOptionPane.showMessageDialog(this, "Đăng nhập thất bại! Vui lòng kiểm tra lại tên đăng nhập và mật khẩu.");
//}
//        } catch (Exception ex) {
//            Logger.getLogger(DangNhapAD.class.getName()).log(Level.SEVERE, null, ex);
//        }


    String tenDN = txtTenDN.getText().trim();
    String matKhau = new String(txtMatKhau.getPassword()).trim();

    if (tenDN.isEmpty() || matKhau.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Vui lòng nhập tên đăng nhập và mật khẩu.");
        return;
    }

    LoginDAO loginDAO = new LoginDAO();
    UserAD user = null;
    try {
        user = loginDAO.login(tenDN, matKhau);
    } catch (Exception ex) {
        Logger.getLogger(DangNhapAD.class.getName()).log(Level.SEVERE, null, ex);
    }

    if (user != null) {
        JOptionPane.showMessageDialog(this, "Đăng nhập thành công!");
        
        GiaoDienTEA mainFrame = new GiaoDienTEA(tenDN); // Truyền tên đăng nhập vào form chính
        mainFrame.setVisible(true);
        if (user.isAdmin()) {
            // Cấp quyền admin
            mainFrame.setAdminRights();
        } else {
            // Cấp quyền user
            mainFrame.setUserRights(user);
        }

        mainFrame.setVisible(true);
        this.dispose(); // Đóng form đăng nhập
    } else {
        JOptionPane.showMessageDialog(this, "Tên đăng nhập hoặc mật khẩu không đúng.");
    }
    }//GEN-LAST:event_btnDangNhapActionPerformed

    private void chkShowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkShowActionPerformed
        // TODO add your handling code here:
                if(chkShow.isSelected()){
            txtMatKhau.setEchoChar((char)0);
        }else{
            txtMatKhau.setEchoChar('\u2022');
        }
    }//GEN-LAST:event_chkShowActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DangNhapAD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DangNhapAD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DangNhapAD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DangNhapAD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DangNhapAD().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDangNhap;
    private javax.swing.JCheckBox chkRemember;
    private javax.swing.JCheckBox chkShow;
    private javax.swing.JLabel dateLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel timeLabel;
    private javax.swing.JPasswordField txtMatKhau;
    private javax.swing.JTextField txtTenDN;
    // End of variables declaration//GEN-END:variables
}
